language: c
compiler: gcc
before_install:
  - locale
before_script:
  - ./configure
  - yes "" | make update
  - make
  - cpan install IO::Socket::IP
script: make test
env:
  global:
    - PERL_MM_USE_DEFAULT=1 # tell CPAN to assume defaults as much as possible
    - PERL5LIB=/home/travis/perl5
addons:
  apt:
    packages:
      - gperf
